//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Instructors = newInstructorsTable("public", "instructors", "")

type instructorsTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnInteger
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type InstructorsTable struct {
	instructorsTable

	EXCLUDED instructorsTable
}

// AS creates new InstructorsTable with assigned alias
func (a InstructorsTable) AS(alias string) *InstructorsTable {
	return newInstructorsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InstructorsTable with assigned schema name
func (a InstructorsTable) FromSchema(schemaName string) *InstructorsTable {
	return newInstructorsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InstructorsTable with assigned table prefix
func (a InstructorsTable) WithPrefix(prefix string) *InstructorsTable {
	return newInstructorsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InstructorsTable with assigned table suffix
func (a InstructorsTable) WithSuffix(suffix string) *InstructorsTable {
	return newInstructorsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInstructorsTable(schemaName, tableName, alias string) *InstructorsTable {
	return &InstructorsTable{
		instructorsTable: newInstructorsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newInstructorsTableImpl("", "excluded", ""),
	}
}

func newInstructorsTableImpl(schemaName, tableName, alias string) instructorsTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
	)

	return instructorsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
