//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Courses = Courses.FromSchema(schema)
	Dislikes = Dislikes.FromSchema(schema)
	Instructors = Instructors.FromSchema(schema)
	Likes = Likes.FromSchema(schema)
	Offerings = Offerings.FromSchema(schema)
	Ratings = Ratings.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	Teaches = Teaches.FromSchema(schema)
	Tokens = Tokens.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
