//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Courses struct {
	ID          int64 `sql:"primary_key"`
	Number      string
	Name        string
	Department  string
	Units       int32
	Description string
}
