//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Offerings struct {
	ID       int64 `sql:"primary_key"`
	CourseID int64
	Semester SemesterType
	Year     int32
	Location string
}
