//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Ratings struct {
	ID         int64 `sql:"primary_key"`
	UserID     int64
	OfferingID int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Overall    int32
	Teaching   int32
	Materials  int32
	Value      int32
	Difficulty int32
	Workload   int32
	Grading    int32
	Comment    string
}
