//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tokens struct {
	ID        int64 `sql:"primary_key"`
	Hash      []byte
	UserID    int64
	CreatedAt time.Time
	Expiry    time.Time
	Scope     ScopeType
}
