//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ScopeType = &struct {
	Act  postgres.StringExpression
	Auth postgres.StringExpression
	Pwd  postgres.StringExpression
}{
	Act:  postgres.NewEnumValue("ACT"),
	Auth: postgres.NewEnumValue("AUTH"),
	Pwd:  postgres.NewEnumValue("PWD"),
}
