//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var SemesterType = &struct {
	Fall    postgres.StringExpression
	Spring  postgres.StringExpression
	Summer1 postgres.StringExpression
	Summer2 postgres.StringExpression
	Winter  postgres.StringExpression
}{
	Fall:    postgres.NewEnumValue("Fall"),
	Spring:  postgres.NewEnumValue("Spring"),
	Summer1: postgres.NewEnumValue("Summer 1"),
	Summer2: postgres.NewEnumValue("Summer 2"),
	Winter:  postgres.NewEnumValue("Winter"),
}
